### ISSUE TITLE
デバッグ用のprintを削除しログ出力をする

### ISSUE THREAD

**Issue by takanory** [khajime/fruit-sales-management-console#10]
## 目的

* サーバーの処理経過を出力する場合はprintではなくliggingを使用する
* djangoだと設定ファイルでログの出力先とか設定できて便利

## 内容

* https://github.com/khajime/fruit-sales-management-console/blob/master/fruitsales/views.py#L78
* デバッグ用っぽいprintが入っているので削除する
* できれば: loggingモジュールをしてログ出力を行う

**Comment by khajime** [comment]
loggingでDEBUGレベルに出力するようにします。
開発版ということで出力先はコンソールに。
