### ISSUE TITLE
必須: DBを毎回検索しているのを改修する

### ISSUE THREAD

**Issue by takanory** [khajime/fruit-sales-management-console#12]
## 目的

* 売上を集計する処理で、集計処理ごとにDBから全件取得しているため効率が悪い
* 一度だけ全件を取得して、あとはプログラムで処理する形式に変更する

## 内容

* https://github.com/khajime/fruit-sales-management-console/blob/master/stats/utils.py#L15
* `Sale.objects.all()` を一度だけ呼ぶようにする

**Comment by khajime** [comment]
よく考えると私がcloseしたら駄目ですね。
