### ISSUE TITLE
チェックしている内容とメッセージがあっていない

### ISSUE THREAD

**Issue by takanory** [khajime/fruit-sales-management-console#13]
## 目的

* コードのイモトエラーメッセージがあっていないので合わせる

## 内容

* https://github.com/khajime/fruit-sales-management-console/blob/master/fruitsales/models.py#L31-L32

**Comment by khajime** [comment]
テストの方ではエラーが出ることしか確認していないため見逃されていたようですね。
できれば今後、メッセージ内容もテストできるように修正したいところです。
というわけで https://github.com/khajime/fruit-sales-management-console/issues/16 追加しました。
